//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCA.Telehealth.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTCA.Telehealth.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MS_Teams_Telehealth___Join_from_an_Android {
            get {
                object obj = ResourceManager.GetObject("MS_Teams_Telehealth___Join_from_an_Android", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MS_Teams_Telehealth___Join_from_an_iPhone {
            get {
                object obj = ResourceManager.GetObject("MS_Teams_Telehealth___Join_from_an_iPhone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Patient_Telehealth_Guide_for_MS_Teams {
            get {
                object obj = ResourceManager.GetObject("Patient_Telehealth_Guide_for_MS_Teams", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;!--[if gte mso 9]&gt;&lt;xml&gt;&lt;o:OfficeDocumentSettings&gt;&lt;o:AllowPNG/&gt;&lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;&lt;/o:OfficeDocumentSettings&gt;&lt;/xml&gt;&lt;![endif]--&gt;
        ///	&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///	&lt;meta content=&quot;width=device- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatientEmail {
            get {
                return ResourceManager.GetString("PatientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;!--[if gte mso 9]&gt;&lt;xml&gt;&lt;o:OfficeDocumentSettings&gt;&lt;o:AllowPNG/&gt;&lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;&lt;/o:OfficeDocumentSettings&gt;&lt;/xml&gt;&lt;![endif]--&gt;
        ///&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot;/&gt;
        ///&lt;meta content=&quot;width=devic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatientEmailTemplate {
            get {
                return ResourceManager.GetString("PatientEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;Your Tech Support Call with CTCA&lt;/title&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/* CLIENT-SPECIFIC STYLES ------------------- */
        ///
        ///		#outlook a {
        ///			padding: 0;
        ///			/* Force Outlook to provide a &quot;view in browser&quot; message */
        ///		}
        ///
        ///		.ReadMsgBody {
        ///			width: 100%;
        ///			/* Force Hotmail to display emails at full width */
        ///		}
        ///
        ///		.ExternalClass {
        ///			width: 100%;
        ///			/* Force Hotmail t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadinessCheckEmailv2 {
            get {
                return ResourceManager.GetString("ReadinessCheckEmailv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;Your Upcoming Telehealth Video Appointment with CTCA&lt;/title&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/* CLIENT-SPECIFIC STYLES ------------------- */
        ///
        ///		#outlook a {
        ///			padding: 0;
        ///			/* Force Outlook to provide a &quot;view in browser&quot; message */
        ///		}
        ///
        ///		.ReadMsgBody {
        ///			width: 100%;
        ///			/* Force Hotmail to display emails at full width */
        ///		}
        ///
        ///		.ExternalClass {
        ///			width: 100%;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TelehealthEmailv2 {
            get {
                return ResourceManager.GetString("TelehealthEmailv2", resourceCulture);
            }
        }
    }
}
