// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CTCA.Telehealth.Microsoft.Models;
//
//    var sendGridSendEmailPayload = SendGridSendEmailPayload.FromJson(jsonString);

namespace CTCA.Telehealth.Twilio.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SendGridSendEmailPayload
    {
        [JsonProperty("from")]
        public From From { get; set; }

        [JsonProperty("personalizations")]
        public List<Personalization> Personalizations { get; set; }

        [JsonProperty("template_id")]
        public string TemplateId { get; set; }
    }

    public partial class From
    {
        [JsonProperty("email")]
        public string Email { get; set; }
    }

    public partial class Personalization
    {
        [JsonProperty("to")]
        public List<From> To { get; set; }

        [JsonProperty("dynamic_template_data")]
        public object DynamicTemplateData { get; set; }
    }

    public partial class SendGridSendEmailPayload
    {
        public static SendGridSendEmailPayload FromJson(string json) => JsonConvert.DeserializeObject<SendGridSendEmailPayload>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SendGridSendEmailPayload self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
