//
//  CTCAAnalyticsConstants.swift
//  myctca
//
//  Created by Manjunath K on 10/5/20.
//  Copyright © 2020 CTCA. All rights reserved.
//

import Foundation

struct CTCAAnalyticsConstants {
    //PAGE_<Page_title>_VIEW
    //ACTION_<Name>_TAP
    //ALERT_<Alert_name>_<For success or failure>
    
    //Exceptions
    static let EXCEPTION_REST_API = "EXCEPTION_REST_API"
    static let EXCEPTION_SYSTEM_THROWN = "EXCEPTION_SYSTEM_THROWN"
    
    //login
    static let PAGE_SIGNIN_VIEW = "PAGE_SIGNIN_VIEW"
    
    static let ACTION_SIGNIN_TAP = "ACTION_SIGNIN_TAP"
    static let ACTION_SHOW_PASSWORD_TAP = "ACTION_SHOW_PASSWORD_TAP"
    static let ACTION_FORGOT_PASSWORD_TAP = "ACTION_FORGOT_PASSWORD_TAP"
    static let ACTION_TOUCHID_TAP = "ACTION_TOUCHID_TAP"
    static let ACTION_TERMS_CONDITIONS_TAP = "ACTION_TERMS_CONDITIONS_TAP"
    static let ACTION_PRIVACY_POLICY_TAP = "ACTION_PRIVACY_POLICY_TAP"
    static let ACTION_CREATE_ACCOUNT_TAP = "ACTION_CREATE_ACCOUNT_TAP"
    static let ACTION_LOGIN_CALL_TAP = "ACTION_LOGIN_CALL_TAP"
    static let ACTION_LOGIN_SEND_MESSAGE_GOTO_TAP = "ACTION_LOGIN_SEND_MESSAGE_GOTO_TAP"
    
    static let ALERT_SIGNIN_FAIL = "ALERT_SIGNIN_FAIL"
    static let LOGIN_TIMEOUT_ERROR = "LOGIN_TIMEOUT_ERROR"
    static let LOGIN_INCORRECT_CREDENTIALS = "LOGIN_INCORRECT_CREDENTIALS"
    static let LOGIN_LOCKED_ACCOUNT = "LOGIN_LOCKED_ACCOUNT"
    static let LOGIN_REST_API_FAILURE = "LOGIN_REST_API_FAILURE"
    
    //send message
    static let PAGE_SEND_MESSAGE_VIEW = "PAGE_SEND_MESSAGE_VIEW"
    static let ACTION_SEND_MESSAGE_TAP = "ACTION_SEND_MESSAGE_TAP"
    
    static let ALERT_SEND_MESSAGE_SUCCESS = "ALERT_SEND_MESSAGE_SUCCESS"
    static let ALERT_SEND_MESSAGE_FAIL = "ALERT_SEND_MESSAGE_FAIL"
    
    //Terms of Use
    static let PAGE_TERMS_OF_USE_VIEW = "PAGE_TERMS_OF_USE_VIEW"
    
    static let ACTION_ACCEPT_TERMS_OF_USE_TAP = "ACTION_ACCEPT_TERMS_OF_USE_TAP"
    static let ACTION_DECLINE_TERMS_OF_USE_TAP = "ACTION_DECLINE_TERMS_OF_USE_TAP"
    
    //Home
    static let PAGE_HOME_PATIENT_VIEW = "PAGE_HOME_PATIENT_VIEW"
    static let PAGE_HOME_CAREGIVER_VIEW = "PAGE_HOME_CAREGIVER_VIEW"
    
    static let ACTION_GOTO_PORTAL_TAP = "ACTION_GOTO_PORTAL_TAP"
    static let ACTION_SIGNOUT_CAREGIVER_TAP = "ACTION_SIGNOUT_CAREGIVER_TAP"
    
    //appoitments
    static let PAGE_PAST_APPOINTMENTS_VIEW = "PAGE_PAST_APPOINTMENTS_VIEW"
    static let PAGE_FUTURE_APPOINTMENTS_VIEW = "PAGE_FUTURE_APPOINTMENTS_VIEW"
    static let PAGE_APPOINTMENTS_DETAILS_VIEW = "PAGE_APPOINTMENTS_DETAILS_VIEW"
    static let PAGE_APPOINTMENTS_CANCEL_VIEW = "PAGE_APPOINTMENTS_CANCEL_VIEW"
    static let PAGE_APPOINTMENTS_RESCHEDULE_VIEW = "PAGE_APPOINTMENTS_RESCHEDULE_VIEW"
    static let PAGE_APPOINTMENTS_REQUEST_VIEW = "PAGE_APPOINTMENTS_REQUEST_VIEW"
    static let PAGE_APPOINTMENTS_FILTER_VIEW = "PAGE_APPOINTMENTS_FILTER_VIEW"
    
    static let ACTION_APPOINTMENTS_REQUEST_TAP = "ACTION_APPOINTMENTS_REQUEST_TAP"
    static let ACTION_APPOINTMENTS_DETAIL_TAP = "ACTION_APPOINTMENTS_DETAIL_TAP"
    static let ACTION_APPOINTMENTS_CANCEL_TAP = "ACTION_APPOINTMENTS_CANCEL_TAP"
    static let ACTION_APPOINTMENTS_RESCHEDULE_TAP = "ACTION_APPOINTMENTS_RESCHEDULE_TAP"
    static let ACTION_APPOINTMENTS_REQUEST_SEND_TAP = "ACTION_APPOINTMENTS_REQUEST_SEND_TAP"
    static let ACTION_APPOINTMENTS_CANCEL_SEND_TAP = "ACTION_APPOINTMENTS_CANCEL_SEND_TAP"
    static let ACTION_APPOINTMENTS_RESCHEDULE_SEND_TAP = "ACTION_APPOINTMENTS_RESCHEDULE_SEND_TAP"
    static let ACTION_APPOINTMENTS_DOWNLOAD_TAP = "ACTION_APPOINTMENTS_DOWNLOAD_TAP"
    static let ACTION_APPOINTMENTS_TELEHEALTH_JOINNOW_TAP = "ACTION_APPOINTMENTS_TELEHEALTH_JOINNOW_TAP"
    static let ACTION_APPOINTMENTS_TELEHEALTH_SETUP_TAP = "ACTION_APPOINTMENTS_TELEHEALTH_SETUP_TAP"
    
    static let ALERT_APPOINTMENTS_RESCHEDULE_SUCCESS = "ALERT_APPOINTMENTS_RESCHEDULE_SUCCESS"
    static let ALERT_APPOINTMENTS_RESCHEDULE_FAIL = "ALERT_APPOINTMENTS_RESCHEDULE_FAIL"
    static let ALERT_APPOINTMENTS_CANCEL_SUCCESS = "ALERT_APPOINTMENTS_CANCEL_SUCCESS"
    static let ALERT_APPOINTMENTS_CANCEL_FAIL = "ALERT_APPOINTMENTS_CANCEL_FAIL"
    static let ALERT_APPOINTMENTS_REQUEST_SUCCESS = "ALERT_APPOINTMENTS_REQUEST_SUCCESS"
    static let ALERT_APPOINTMENTS_REQUEST_FAIL = "ALERT_APPOINTMENTS_REQUEST_FAIL"
    
    static let ACTION_APPOINTMENTS_PDF_SAVE_TAP = "ACTION_APPOINTMENTS_PDF_SAVE_TAP"
    static let ACTION_APPOINTMENTS_PDF_COPY_TAP = "ACTION_APPOINTMENTS_PDF_COPY_TAP"
    static let ACTION_APPOINTMENTS_PDF_PRINT_TAP = "ACTION_APPOINTMENTS_PDF_PRINT_TAP"
    
    static let ACTION_APPOINTMENTS_PDF_SHARE_TAP = "ACTION_APPOINTMENT_PDF_SHARE_TAP"
    static let ACTION_APPOINTMENTS_PDF_CLOSE_SHARE_TAP = "ACTION_APPOINTMENT_PDF_CLOSE_SHARE_TAP"
    static let ACTION_APPOINTMENT_PDF_AIRDROP_TAP = "ACTION_APPOINTMENT_PDF_AIRDROP_TAP"
    static let ACTION_APPOINTMENT_PDF_MAIL_TAP = "ACTION_APPOINTMENT_PDF_MAIL_TAP"
    static let ACTION_APPOINTMENT_PDF_PRINT_TAP = "ACTION_APPOINTMENT_PDF_PRINT_TAP"
    static let ACTION_APPOINTMENT_PDF_SAVE_TAP = "ACTION_APPOINTMENT_PDF_SAVE_TAP"
    static let ACTION_APPOINTMENT_PDF_COPY_TAP = "ACTION_APPOINTMENT_PDF_COPY_TAP"
    static let ACTION_APPOINTMENT_PDF_SAVE_TO_PHONE_TAP = "ACTION_APPNT_PDF_SAVE_TO_PHONE_TAP"
    static let ACTION_APPOINTMENT_PDF_OTHER_ACTION_TAP = "ACTION_APPNT_PDF_OTHER_ACTION_TAP"

    //lab results
    static let PAGE_LAB_RESULTS_VIEW = "PAGE_LAB_RESULTS_VIEW"
    static let PAGE_LAB_RESULT_DETAIL_VIEW = "PAGE_LAB_RESULT_DETAIL_VIEW"
    static let PAGE_LAB_RESULT_PDF_VIEW = "PAGE_LAB_RESULT_PDF_VIEW"
    
    static let ACTION_LAB_RESULT_DOWNLOAD_TAP = "ACTION_LAB_RESULT_DOWNLOAD_TAP"
    
    static let ACTION_LAB_RESULTS_PDF_SAVE_TAP = "ACTION_LAB_RESULTS_PDF_SAVE_TAP"
    static let ACTION_LAB_RESULTS_PDF_COPY_TAP = "ACTION_LAB_RESULTS_PDF_COPY_TAP"
    static let ACTION_LAB_RESULTS_PDF_PRINT_TAP = "ACTION_LAB_RESULTS_PDF_PRINT_TAP"
    
    //Mail
    static let PAGE_MAIL_INBOX_VIEW = "PAGE_MAIL_INBOX_VIEW"
    static let PAGE_MAIL_SENT_VIEW = "PAGE_MAIL_SENT_VIEW"
    static let PAGE_MAIL_ARCHIVED_VIEW = "PAGE_MAIL_ARCHIVED_VIEW"
    static let PAGE_MAIL_DETAIL_VIEW = "PAGE_MAIL_DETAIL_VIEW"
    static let PAGE_MAIL_NEW_VIEW = "PAGE_MAIL_NEW_VIEW"

    static let ACTION_NEW_MAIL_TAP = "ACTION_NEW_MAIL_TAP"
    static let ACTION_NEW_MAIL_SEND_TAP = "ACTION_NEW_MAIL_SEND_TAP"
    static let ACTION_MAIL_DETAIL_TAP = "ACTION_MAIL_DETAIL_TAP"
    static let ACTION_MAIL_REPLY_TAP = "ACTION_MAIL_REPLY_TAP"
    static let ACTION_MAIL_ARCHIVE_TAP = "ACTION_MAIL_ARCHIVE_TAP"
    static let ACTION_MAIL_MARKREAD_TAP = "ACTION_MAIL_MARKREAD_TAP"
    
    static let ALERT_NEW_MAIL_SUCCESS = "ALERT_NEW_MAIL_SUCCESS"
    static let ALERT_NEW_MAIL_FAIL = "ALERT_NEW_MAIL_FAIL"
    
    //More
    //Main menu
    static let ACTION_MORE_TAP = "ACTION_MORE_TAP"
    static let ACTION_MORE_MED_DOCS_TAP = "ACTION_MORE_MED_DOCS_TAP"
    static let ACTION_MORE_HEALTH_HISTORY_TAP = "ACTION_MORE_HEALTH_HISTORY_TAP"
    static let ACTION_MORE_FORMS_LIBRARY_TAP = "ACTION_MORE_FORMS_LIBRARY_TAP"
    static let ACTION_MORE_BILL_PAY_TAP = "ACTION_MORE_BILL_PAY_TAP"
    static let ACTION_MORE_USER_PROFILE_TAP = "ACTION_MORE_USER_PROFILE_TAP"
    static let ACTION_MORE_ACTIVITY_LOGS_TAP = "ACTION_MORE_ACTIVITY_LOGS_TAP"
    static let ACTION_MORE_CONTACT_US_TAP = "ACTION_MORE_CONTACT_US_TAP"
    static let ACTION_MORE_ABOUT_MY_CTCA_TAP = "ACTION_MORE_ABOUT_MY_CTCA_TAP"
    static let ACTION_MORE_SIGNOUT_TAP = "ACTION_MORE_SIGNOUT_TAP"
    
    //Med Docs
    static let PAGE_CARE_PLAN_VIEW = "PAGE_CARE_PLAN_VIEW"
    
    static let PAGE_CS_VIEW = "PAGE_CS_VIEW"
    static let PAGE_CS_DETAIL_VIEW = "PAGE_CS_DETAIL_VIEW"
    static let PAGE_CS_DOWNLOAD_VIEW = "PAGE_CS_DOWNLOAD_VIEW"
    static let PAGE_CS_TRANSMIT_VIEW = "PAGE_CS_TRANSMIT_VIEW"
    static let PAGE_CS_FILTER_VIEW = "PAGE_CS_FILTER_VIEW"
        
    //for buttons on list view and detail view
    static let ACTION_CS_GOTO_TRANSMIT_TAP = "ACTION_CS_GOTO_TRANSMIT_TAP"
    static let ACTION_CS_GOTO_DOWNLOAD_TAP = "ACTION_CS_GOTO_DOWNLOAD_TAP"
    static let ACTION_CS_GOTO_CANCEL_TAP = "ACTION_CS_GOTO_CANCEL_TAP"
    static let ACTION_CS_FILTER_APPLY_TAP = "ACTION_CS_FILTER_APPLY_TAP"
    
    //for buttons on Transmit Page
    static let ACTION_CS_TRANSMIT_TAP = "ACTION_CS_TRANSMIT_TAP"
    static let ACTION_CS_TRANSMIT_CANCEL_TAP = "ACTION_CS_TRANSMIT_CANCEL_TAP"
    
    //for buttons on Download Page
    static let ACTION_CS_DOWNLOAD_CANCEL_TAP = "ACTION_CS_DOWNLOAD_CANCEL_TAP"
    static let ACTION_CS_DOWNLOAD_TAP = "ACTION_CS_DOWNLOAD_TAP"
    
    //Alert on after download
    static let ALERT_CS_DOWNLOAD_SUCCESS = "ALERT_CS_DOWNLOAD_SUCCESS"
    static let ALERT_CS_DOWNLOAD_FAIL = "ALERT_CS_DOWNLOAD_FAIL"
    static let ACTION_CS_DOWNLOADED_ZIP_CANCEL = "ACTION_CS_DOWNLOADED_ZIP_CANCEL"
    static let ACTION_CS_DOWNLOAD_ZIP_SAVE = "ACTION_CS_DOWNLOAD_ZIP_SAVE"
        
    //Alert on after transmit
    static let ALERT_CS_TRANSMIT_SUCCESS = "ALERT_CS_TRANSMIT_SUCCESS"
    static let ALERT_CS_TRANSMIT_FAIL = "ALERT_CS_TRANSMIT_FAIL"
    
    static let PAGE_CLINICAL_VIEW = "PAGE_CLINICAL_VIEW"
    static let PAGE_CLINICAL_DETAIL_VIEW = "PAGE_CLINICAL_DETAIL_VIEW"
    
    static let PAGE_RADIATION_VIEW = "PAGE_RADIATION_VIEW"
    static let PAGE_RADIATION_DETAIL_VIEW = "PAGE_RADIATION_DETAIL_VIEW"
    
    static let PAGE_IMAGING_VIEW = "PAGE_IMAGING_VIEW"
    static let PAGE_IMAGING_DETAIL_VIEW = "PAGE_IMAGING_DETAIL_VIEW"

    static let PAGE_INTEGRATIVE_VIEW = "PAGE_INTEGRATIVE_VIEW"
    static let PAGE_INTEGRATIVE_DETAIL_VIEW = "PAGE_INTEGRATIVE_DETAIL_VIEW"
    
    //vitals
    static let PAGE_VITALS_VIEW = "PAGE_VITALS_VIEW"
    
    static let PAGE_PRESCRIPTIONS_VIEW = "PAGE_PRESCRIPTIONS_VIEW"
    static let PAGE_PRESCRIPTION_DETAILS_VIEW = "PAGE_PRESCRIPTION_DETAILS_VIEW"
    static let PAGE_PRESCRIPTION_RENEWAL_VIEW = "PAGE_PRESCRIPTION_RENEWAL_VIEW"
    
    static let ACTION_PRESCRIPTIONS_INCLUDE_TAP = "ACTION_PRESCRIPTIONS_INCLUDE_TAP"
    static let ACTION_PRESCRIPTION_RENEWAL_GOTO_TAP = "ACTION_PRESCRIPTION_RENEWAL_GOTO_TAP"
    static let ACTION_PRESCRIPTION_RENEWAL_SEND_TAP = "ACTION_PRESCRIPTION_RENEWAL_SEND_TAP"
    
    static let ALERT_PRESCRIPTION_RENEWAL_SUCCESS = "ALERT_PRESCRIPTION_RENEWAL_SUCCESS"
    static let ALERT_PRESCRIPTION_RENEWAL_FAIL = "ALERT_PRESCRIPTION_RENEWAL_FAIL"
    
    static let PAGE_ALLERGIES_VIEW = "PAGE_ALLERGIES_VIEW"
    static let PAGE_IMMUNIZATIONS_VIEW = "PAGE_IMMUNIZATIONS_VIEW"
    static let PAGE_HEALTH_ISSUES_VIEW = "PAGE_HEALTH_ISSUES_VIEW"
    
    //Forms
    static let PAGE_ROI_BASE_VIEW = "PAGE_ROI_BASE_VIEW"
    static let PAGE_ROI_FORM_VIEW = "PAGE_ROI_FORM_VIEW"
    static let PAGE_ROI_FORM_PDF_VIEW = "PAGE_ROI_FORM_PDF_VIEW"
    
    static let ACTION_ROI_DOWNLOAD_TAP = "ACTION_ROI_DOWNLOAD_TAP"
    static let ACTION_ROI_SUBMIT_TAP = "ACTION_ROI_SUBMIT_TAP"
    static let ACTION_ROI_SEND_TAP = "ACTION_ROI_SEND_TAP"
    
    static let ALERT_ROI_SUBMIT_SUCCESS = "ALERT_ROI_SUBMIT_SUCCESS"
    static let ALERT_ROI_SUBMIT_FAIL = "ALERT_ROI_SUBMIT_FAIL"
    static let ALERT_ROI_DOWNLOAD_FAIL = "ALERT_ROI_DOWNLOAD_FAIL"
    
    static let ACTION_ROI_PDF_SAVE_TAP = "ACTION_ROI_PDF_SAVE_TAP"
    static let ACTION_ROI_PDF_COPY_TAP = "ACTION_ROI_PDF_COPY_TAP"
    static let ACTION_ROI_PDF_PRINT_TAP = "ACTION_ROI_PDF_PRINT_TAP"
    
    static let PAGE_ANNC_BASE_VIEW = "PAGE_ANNC_BASE_VIEW"
    static let PAGE_ANNC_FORM_VIEW = "PAGE_ANNC_FORM_VIEW"
    static let PAGE_ANNC_FORM_PDF_VIEW = "PAGE_ANNC_FORM_PDF_VIEW"
    
    static let ACTION_ANNC_DOWNLOAD_TAP = "ACTION_ANNC_DOWNLOAD_TAP"
    static let ACTION_ANNC_SUBMIT_TAP = "ACTION_ANNC_SUBMIT_TAP"
    static let ACTION_ANNC_SEND_TAP = "ACTION_ANNC_SEND_TAP"
    
    static let ALERT_ANNC_SUBMIT_SUCCESS = "ALERT_ANNC_SUBMIT_SUCCESS"
    static let ALERT_ANNC_SUBMIT_FAIL = "ALERT_ANNC_SUBMIT_FAIL"
    static let ALERT_ANNC_DOWNLOAD_FAIL = "ALERT_ANNC_DOWNLOAD_FAIL"
    
    static let ACTION_ANNC_PDF_SAVE_TAP = "ACTION_ANNC_PDF_SAVE_TAP"
    static let ACTION_ANNC_PDF_COPY_TAP = "ACTION_ANNC_PDF_COPY_TAP"
    static let ACTION_ANNC_PDF_PRINT_TAP = "ACTION_ANNC_PDF_PRINT_TAP"
    
    //Bill PAY
    static let PAGE_BILL_PAY_VIEW = "PAGE_BILL_PAY_VIEW"
    
    static let ACTION_BILL_PAY_TAP = "ACTION_BILL_PAY_TAP"
    
    //activity logs
    static let PAGE_ACTIVITY_LOG_VIEW = "PAGE_ACTIVITY_LOG_VIEW"
    
    static let ACTION_ACTIVITY_LOG_APPLY_FILTER_TAP = "ACTION_ACTIVITY_LOG_APPLY_FILTER_TAP"
    
    //contact us
    static let PAGE_CONTACT_US_VIEW = "PAGE_CONTACT_US_VIEW"
    
    static let ACTION_CALL_MAIN_PHONE_TAP = "ACTION_CALL_MAIN_PHONE_TAP"
    static let ACTION_CALL_SCHEDULING_TAP = "ACTION_CALL_SCHEDULING_TAP"
    static let ACTION_CALL_ACCOMODATIONS_TAP = "ACTION_CALL_ACCOMODATIONS_TAP"
    static let ACTION_CALL_TRANSPORTATIONS_TAP = "ACTION_CALL_TRANSPORTATIONS_TAP"
    static let ACTION_CALL_ROI_TAP = "ACTION_CALL_ROI_TAP"
    static let ACTION_MAP_ADDR_TAP = "ACTION_MAP_ADDR_TAP"
    static let ACTION_CALL_TECH_SUPPORT_TAP = "ACTION_CALL_TECH_SUPPORT_TAP"
    static let ACTION_CONTACT_US_SEND_MESSAGE_TAP = "ACTION_CONTACT_US_SEND_MESSAGE_TAP"
    
    //about
    static let PAGE_ABOUT_MYCTCA_VIEW = "PAGE_ABOUT_MYCTCA_VIEW"
    static let PAGE_ABOUT_MYCTCA_CERT_VIEW = "PAGE_ABOUT_MYCTCA_CERT_VIEW"
    
    static let ACTION_ABOUT_MYCTCA_TERMS_OF_USE_TAP = "ACTION_ABOUT_MYCTCA_TERMS_OF_USE_TAP"
    static let ACTION_ABOUT_MYCTCA_PRIVACY_POLICY_TAP = "ACTION_ABOUT_MYCTCA_PRIVACY_POLICY_TAP"
    static let ACTION_ABOUT_MYCTCA_CERTIFICATION_TAP = "ACTION_ABOUT_MYCTCA_CERTIFICATION_TAP"
    
    //others
    static let ALERT_ACCEPT_ANALYTICS_REPORTING_YES = "ALERT_ACCEPT_ANALYTICS_REPORTING_YES"
    static let ALERT_ACCEPT_ANALYTICS_REPORTING_NO = "ALERT_ACCEPT_ANALYTICS_REPORTING_NO"
    
    static let ALERT_SESSION_RENEWAL_YES = "ALERT_SESSION_RENEWAL_YES"
    static let ALERT_SESSION_RENEWAL_NO = "ALERT_SESSION_RENEWAL_NO"
    
    //Telehealth
    static let ACTION_TELEHEALTH_JON_NOW_TAP = "ACTION_TELEHEALTH_JON_NOW_TAP"
    static let PAGE_TELEHEALTH_MEETING = "PAGE_TELEHEALTH_MEETING"
    static let DURATION_TELEHEALTH_JOIN_MEETING = "DURATION_TELEHEALTH_JOIN_MEETING"
    static let DURATION_TELEHEALTH_PATIENT_IN_LOBBY = "DURATION_TELEHEALTH_PATIENT_IN_LOBBY"
    static let  DURATION_TELEHEALTH_TOTAL_MEETING = "DURATION_TELEHEALTH_TOTAL_MEETING"
    static let  EXCEPTION_TELEHEALTH_MEETING_INTRUPTED = "EXCEPTION_TELEHEALTH_MEETING_INTRUPTED"
    static let  ACTION_TELEHEALTH_VIDEO_ON = "ACTION_TELEHEALTH_VIDEO_ON"
    static let  ACTION_TELEHEALTH_JOIN_ON_WEB = "ACTION_TELEHEALTH_JOIN_ON_WEB"
    
    //12/04/2020 - story#7109
    static let filteredEventList =
    ["EXCEPTION_REST_API",
    "EXCEPTION_SYSTEM_THROWN",
    "ALERT_SIGNIN_FAIL",
    "ALERT_SEND_MESSAGE_SUCCESS",
    "ALERT_SEND_MESSAGE_FAIL",
    "ALERT_APPOINTMENTS_RESCHEDULE_SUCCESS",
    "ALERT_APPOINTMENTS_RESCHEDULE_FAIL",
    "ALERT_APPOINTMENTS_CANCEL_SUCCESS",
    "ALERT_APPOINTMENTS_CANCEL_FAIL",
    "ALERT_APPOINTMENTS_REQUEST_SUCCESS",
    "ALERT_APPOINTMENTS_REQUEST_FAIL",
    "ALERT_NEW_MAIL_SUCCESS",
    "ALERT_NEW_MAIL_FAIL",
    "ALERT_CS_DOWNLOAD_SUCCESS",
    "ALERT_CS_DOWNLOAD_FAIL",
    "ALERT_CS_TRANSMIT_SUCCESS",
    "ALERT_CS_TRANSMIT_FAIL",
    "ALERT_PRESCRIPTION_RENEWAL_SUCCESS",
    "ALERT_PRESCRIPTION_RENEWAL_FAIL",
    "ALERT_ROI_SUBMIT_SUCCESS",
    "ALERT_ROI_SUBMIT_FAIL",
    "ALERT_ROI_DOWNLOAD_FAIL",
    "ALERT_ANNC_SUBMIT_SUCCESS",
    "ALERT_ANNC_SUBMIT_FAIL",
    "ALERT_ANNC_DOWNLOAD_FAIL",
    "ACTION_TELEHEALTH_JON_NOW_TAP",
     "PAGE_TELEHEALTH_MEETING",
     "DURATION_TELEHEALTH_JOIN_MEETING",
     "DURATION_TELEHEALTH_PATIENT_IN_LOBBY",
     "DURATION_TELEHEALTH_TOTAL_MEETING",
     "EXCEPTION_TELEHEALTH_MEETING_INTRUPTED",
     "ACTION_TELEHEALTH_VIDEO_ON",
     "ACTION_TELEHEALTH_JOIN_ON_WEB",
     "ACTION_APPOINTMENT_PDF_SHARE_TAP",
     "ACTION_APPOINTMENT_PDF_CLOSE_SHARE_TAP",
     "ACTION_APPOINTMENT_PDF_AIRDROP_TAP",
     "ACTION_APPOINTMENT_PDF_MAIL_TAP",
      "ACTION_APPOINTMENT_PDF_PRINT_TAP",
      "ACTION_APPOINTMENT_PDF_SAVE_TAP",
      "ACTION_APPOINTMENT_PDF_COPY_TAP",
     "ACTION_APPOINTMENT_PDF_SAVE_TO_PHONE_TAP",
     "ACTION_APPOINTMENT_PDF_OTHER_ACTION_TAP"
    ]
}

    
